web:
  image: nginx
  ports: 
   - "80:80"
  volumes:
   - ./src:/var/www/
   - ./src/mage2.conf:/etc/nginx/conf.d/default.conf
  links:
   - php56
php56:
  image: php:5-fpm
  volumes:
   - ./src/public:/var/www/public