web:
  image: nginx
  ports: 
   - "80:80"
  volumes:
   - ./src:/var/www/
   - ./src/mage2.conf:/etc/nginx/conf.d/default.conf
  links:
   - php56
php56:
  image: php56-magento2-xdebug
  volumes:
   - ./src/public:/var/www/public
  links:
   - mysql56
mysql56:
  image: mysql:5.6
  volumes:
     - /var/lib/mysql
  environment:
    MYSQL_DATABASE: mage2
    MYSQL_USER: galillei
    MYSQL_PASSWORD: bazilio
    MYSQL_ROOT_PASSWORD: bazilio